version: '3.7'

services:
  db:
    build:
      context: ./src/build/docker/mysql
      dockerfile: ./Dockerfile
    ports:
      - '3336:3306'
    volumes:
      - echo-websocket-mysql-data:/var/lib/mysql
      - ./src/build/docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./src/build/docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8020:8020'
    volumes:
      - $PWD/src:/go/src/app:delegated
    depends_on:
      - db
    tty: true
    env_file:
      - .env

  proxy:
    build:
      context: ./src/build/docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./src/build/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  echo-websocket-mysql-data:
